<a href="https://colab.research.google.com/github/sandrakaku/ml0930/blob/master/RNN_family.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [4]:
# Sample: 1
# Sequence Length: 5
# feature dimension: 8

inputs = tf.random.normal([1, 5, 8])

# tf.keras.layers.LSTM

In [5]:
output = layers.LSTM(units=3)(inputs)
print(output.shape)

(1, 3)


In [6]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(3, return_sequences=True, return_state=True)(inputs)

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.1619989   0.02559346  0.2561023 ]
  [-0.05864269  0.06812505 -0.0754921 ]
  [-0.09577419 -0.02111881 -0.07018442]
  [ 0.08240461 -0.0744306   0.01248048]
  [ 0.09575005 -0.05433186 -0.02169498]]], shape=(1, 5, 3), dtype=float32)
final_hiden_state (h):  (1, 3) tf.Tensor([[ 0.09575005 -0.05433186 -0.02169498]], shape=(1, 3), dtype=float32)
final_cell_state (c):  (1, 3) tf.Tensor([[ 0.39537305 -0.6359691  -0.03060528]], shape=(1, 3), dtype=float32)


# tf.keras.layers.GRU

In [7]:
output = layers.GRU(units=3)(inputs) # 設定Unit要幾個
print(output.shape)

(1, 3)


In [8]:
whole_sequence_output, final_state = layers.GRU(3, return_sequences=True, return_state=True)(inputs) # 打開return_sequence和return_state

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.4163862  -0.15563999 -0.09131131]
  [-0.6519987   0.21207014 -0.14881718]
  [ 0.47509643 -0.3039614  -0.32580188]
  [ 0.5876997   0.03608909  0.31574333]
  [ 0.6552513   0.09547674 -0.05786414]]], shape=(1, 5, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[ 0.6552513   0.09547674 -0.05786414]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [9]:
output = layers.Bidirectional(layers.LSTM(10))(inputs)
print(output.shape)

(1, 20)


In [10]:
# merge_mode: Sum
output = layers.Bidirectional(layers.LSTM(10), merge_mode='sum')(inputs)
print(output.shape)

(1, 10)


In [11]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(10, return_sequences=True))(inputs)
print(output.shape)

(1, 5, 20)


In [12]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(2, return_sequences=True, return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 4) tf.Tensor(
[[[ 0.02553687  0.09569987 -0.03582771  0.07830819]
  [ 0.00849148 -0.005376   -0.04002071 -0.15502658]
  [ 0.08417138  0.21719259 -0.05297339 -0.23520029]
  [ 0.06077849  0.3072863  -0.03542757 -0.32942614]
  [-0.00950476  0.07747911  0.11314693 -0.13541614]]], shape=(1, 5, 4), dtype=float32)
forward_h :  (1, 2) tf.Tensor([[-0.00950476  0.07747911]], shape=(1, 2), dtype=float32)
forward_c :  (1, 2) tf.Tensor([[-0.10296938  0.7806246 ]], shape=(1, 2), dtype=float32)
backward_h :  (1, 2) tf.Tensor([[-0.03582771  0.07830819]], shape=(1, 2), dtype=float32)
backward_c :  (1, 2) tf.Tensor([[-0.07258392  0.22250809]], shape=(1, 2), dtype=float32)


## Many-to-one

In [13]:
input = layers.Input(shape=(5, 8))
x = layers.LSTM(5)(input)
ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 5)                 280       
_________________________________________________________________
dense (Dense)                (None, 10)                60        
Total params: 340
Trainable params: 340
Non-trainable params: 0
_________________________________________________________________


In [14]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, return_sequences=True)(input)
x2 = layers.LSTM(256, return_sequences=True)(x1)
x3 = layers.LSTM(10)(x2)
ouput = layers.Dense(10, activation='softmax')(x3)
model = models.Model(input, ouput)
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 5, 128)            70144     
_________________________________________________________________
lstm_8 (LSTM)                (None, 5, 256)            394240    
_________________________________________________________________
lstm_9 (LSTM)                (None, 10)                10680     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
Total params: 475,174
Trainable params: 475,174
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [15]:
input = layers.Input(shape=(50, 8))
x = layers.LSTM(10, return_sequences=True)(input)
output = layers.Dense(20, activation='softmax')(x)
# output = layers.TimeDistributed(layers.Dense(20, activation='softmax'))(x)
model = models.Model(input, output)
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 50, 8)]           0         
_________________________________________________________________
lstm_10 (LSTM)               (None, 50, 10)            760       
_________________________________________________________________
dense_2 (Dense)              (None, 50, 20)            220       
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq